# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InteligenciaGeografica
                                 A QGIS plugin
 Plugin para auxiliar tomada de decisão quanto a localização de empreendimentos levando em conta sua localização espacial.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-11
        copyright            : (C) 2024 by R. A. Szeliga
        email                : rafaelsz@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load InteligenciaGeografica class from file InteligenciaGeografica.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Inteligencia_Geografica import InteligenciaGeografica
    return InteligenciaGeografica(iface)
